db:
  user:     'thuguda'
  pw:       'Ak$hay501'          
  host:     'mysql.clarksonmsda.org'
  db:       'thuguda_FAR'

far:
  departments_root: '/Users/akshaythugudam/Documents/GitHub/Departments'

tables:
  professor:                  'PROFESSOR'
  user:                       'users'
  awards:                     'AWARDS'
  personalawards:             'PERSONALAWARDS'
  studentawards:              'STUDENTAWARDS'
  proposal:                   'PROPOSAL'
  grants:                     'GRANTS'
  teachingevaluation:         'TEACHINGEVALUATION'
  advisingevaluation:         'ADVISINGEVALUATION'
  currentstudents:            'CURRENTSTUDENTS'
  adviseecount:               'ADVISEECOUNT'
  thesis:                     'THESIS'
  service:                    'SERVICE'
  prospectivevisit:           'PROSPECTIVEVISIT'
  professionaldevelopment:    'PROFESSIONALDEVELOPMENT'
  reviews:                    'REVIEWS'
  undergraduateresearch:      'UNDERGRADUATERESEARCH'
  expenditure:                'EXPENDITURE'