db:
  user:      'your_username_here'
  pw:       'your_password_here'          
  host:     'your_host_here'
  db:       'your_database_name_here'

tables:
  professor:                  'PROFESSOR'
  user:                       'users'
  awards:                     'AWARDS'
  personalawards:             'PERSONALAWARDS'
  studentawards:              'STUDENTAWARDS'
  proposal:                   'PROPOSAL'
  grants:                     'GRANTS'
  teachingevaluation:         'TEACHINGEVALUATION'
  advisingevaluation:         'ADVISINGEVALUATION'
  currentstudents:            'CURRENTSTUDENTS'
  adviseecount:               'ADVISEECOUNT'
  thesis:                     'THESIS'
  service:                    'SERVICE'
  prospectivevisit:           'PROSPECTIVEVISIT'
  professionaldevelopment:    'PROFESSIONALDEVELOPMENT'
  reviews:                    'REVIEWS'
  undergraduateresearch:      'UNDERGRADUATERESEARCH'
  expenditure:                'EXPENDITURE'